name: Swift Lint
on:
  pull_request:
    branches: [main]

concurrency:
  group: swiftlint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  swiftlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Lint Swift Files"
        run: Support/Scripts/SwiftLint
        env:
          REPORTER: github-actions-logging
